### ISSUE TITLE
[SERVER] В дуэль сам с собой

### ISSUE THREAD

**Issue by treeDerevo** [treeDerevo/NPvP-Issues#113]
### Опишите баг
Вы можете пойти в дуэль (рейтинг), застрять в дуэли, как бы "пвпхаясь" с противником. Но противника на карте нет.. Вы можете созерцать только пустоту, окружающую вас. Рядом с вами только стены с барьером, холодный воздух с ветром продувает ваше тело, находящееся в доспехах. Душу скорбит печаль, внутри вас ничего. Вы холодно изучаете строение арены, пытаясь проникнуть с помощью вашего снаряжения во всякие дыры. В конце концов, боги соблаговолят вам, и через 5 минут ваших мучений, если вы не совершили самоубийство до этого, вас выкинет из арены.

### Шаги воспроизведения
Опишите, как воспроизвести эту ошибку.
1. Противник включает Авто-Дуэли
2. Противник заходит на дуэль, выигрывает ее или проигрывает.. сути это не меняет.
3. Противник снова заходит на дуэль, его тпает туда автоматически продуманная система авто-дуэлей для донатеров. 
4. Противник не хочет сражаться с вами, и выходит с сервера, потом снова заходит.
5. Вы снова заходите в ваш любимых режим, где вы постоянно играете.
6. Но удивительным образом, Противник снова попадается вам!
7. Однако, Противник уже не с вами в дуэли. Да, у него включена авто-дуэль, он находится на спавне, но Вы уже на арене, пытаясь понять тленность бытия........
8. Вы уже отсидели ваш срок и в надежде найти нормального противника, вы снова идете на режим.
9. Но снова попадете на этого Противника, который включит злополучный Авто-Дуэльный режим. И снова все повторяется, и снова Вселенная повторяет те же приёмы против Вас.

### Поведение системы
**Фактический результат**
Вы наблюдаете и смотрите на звезды в небо, не понимая, что происходит.
**Ожидаемый результат**
Вы наказываете вашего Противника своим длинным, холодным, тяжелым, продолговатым мечом или топором...

### Окружение
 - OS: Это не очень важно для решения таких проблем смертных..
 - Minecraft Version: И это тоже.

**Comment by vindys22895** [comment]
Хуйня сервер я так и знал

**Comment by ipiepiepie** [comment]
### 🛠️ Исправлено!
Теперь на сервере нельзя попасть в одиночную дуэль 😎
