### ISSUE TITLE
[SERVER] Токены не работают при долгом простое.

### ISSUE THREAD

**Issue by treeDerevo** [treeDerevo/NPvP-Issues#114]
### Опишите баг
Токены отключаются от БД при долгом бездействии.

### Шаги воспроизведения
Опишите, как воспроизвести эту ошибку.
1. Перейдите на сервер утром, когда ночью никто не играл.
2. Попробуйте написать /token.

### Поведение системы
**Фактический результат**
Токены выдают ошибку.
**Ожидаемый результат**
Токены выдают токен.

**Comment by ipiepiepie** [comment]
### 🛠️ Исправлено!
Теперь вы можете зарегистрироваться на сайте безо всяких проблем
