### ISSUE TITLE
[WISH] поправить префиксы: сделать замену префикса чата на префикс донатера 

### ISSUE THREAD

**Issue by Stannum05** [treeDerevo/NPvP-Issues#117]
Когда покупаешь донат, у тебя появляется или префикс [P], или [P+], или [S]. Это круто, но вот незадача, префикс чата никто не отменял. Поэтому, когда ты получаешь свой донат и пишешь что-нибудь в чат, у тебя стоят два префикса одного цвета, и смотрится это криво и как недоработка, имхо. В связи с этим пожелание: сделать префиксы донатерам разных цветов, при условии, что цвета будут отличаться от базового желтого, как у префикса чата ([G]), а также сделать так, чтобы префикс мог быть только один и у донатеров префикс чата заменялся на префикс соответсвующего уровня доната.
![Снимок экрана 2022-05-12 в 16 27 30](https://user-images.githubusercontent.com/103384268/168085889-2704485a-db80-4d68-966a-b2019f601889.png)

**Comment by ipiepiepie** [comment]
![image](https://user-images.githubusercontent.com/67694341/169715061-adf0b850-22e9-4e9a-9fb8-248205ae408e.png)
