### ISSUE TITLE
[Wish] Добавить меню с гайдами на сервере

### ISSUE THREAD

**Issue by mishe4ka-5** [treeDerevo/NPvP-Issues#18]
**Ваше пожелание связано с проблемой? Пожалуйста, опишите.**
Я всегда расстраиваюсь, когда не знаю команды сервера

**Опишите желаемое решение**
Добавить на сервер менюшку, где будут указаны основные команды

**Опишите альтернативы, которые вы рассматривали**
Можно добавить на сайт раздел "Википедия"

**Comment by ipiepiepie** [comment]
### ✔️ Добавлена система обучения!
На замену скучным менюшкам с текстом в `/help`, пришла наша **уникальная система обучения**! Войти в режим обучения Вы можете, нажав на **НПС Llely** в лобби
![image](https://user-images.githubusercontent.com/67694341/169715232-3874b3af-a167-41ca-a2ea-7b400d3e280f.png)
