### ISSUE TITLE
[Wish] команда /help не работает

### ISSUE THREAD

**Issue by Stannum05** [treeDerevo/NPvP-Issues#53]
### Опишите баг
прописываю команду /help и вылезает ошибка (см скрин)

### Шаги воспроизведения
Опишите, как воспроизвести эту ошибку.
1. Пропишите в чате /help
2. Увидите ошибку.

### Поведение системы
**Фактический результат**
ничего
**Ожидаемый результат**
список команд или инструкция

### Скриншоты
![Снимок экрана 2022-04-12 в 20 25 21](https://user-images.githubusercontent.com/103384268/163023946-94184894-0435-41c5-89c0-7af2ba89f458.png)

### Окружение
 - OS: IOS
 - Minecraft Version: 1 16 5 оптифайн

**Comment by ipiepiepie** [comment]
### ✔️ Добавлена система обучения!
На замену скучным менюшкам с текстом в `/help`, пришла наша **уникальная система обучения**! Войти в режим обучения Вы можете, нажав на **НПС Llely** в лобби
![image](https://user-images.githubusercontent.com/67694341/169715232-3874b3af-a167-41ca-a2ea-7b400d3e280f.png)
